---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: k8-clusters
  namespace: k8-policies
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
# Cluster selector may need to be refined
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - Other
