---
apiVersion: v1
kind: Namespace
metadata:
  name: compliance-operator
  labels:
    # The compliance operator does not drop all capabilities and run as non root
    # pod-security.kubernetes.io/enforce: restricted
    # pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
---
